### ISSUE TITLE
Refactor Models to take advantage of their Associations

### ISSUE THREAD

**Issue by jameslaneconkling** [CharismaticLupine/CharismaticLupine#46]
I'm not yet 100% on this, but it looks like our routes can be simplified a bit by utilizing model associations--the whole reason we set up `has_many` and `belongs_to` relationships between Photos, Comments, Users, and Physicals.  E.g.

``` javascript
Physical.photos().fetchAll()
//rather than
Photo.where({physical_id: physicalId}).fetchAll()
```

See Bookshelf [documentation](http://bookshelfjs.org/#Model-relations) on associations, though [RoR's guide to it's `Active Record` ORM](http://guides.rubyonrails.org/association_basics.html) goes into more detail on the philosophy of ORM associations.

...although, fuck, just realized this will be difficult, as we don't really have Physical models, thanks to the Bookshelf-PostGIS glitch.

**Comment by RRDuke** [comment]
In that refactor, how do we select the Physical that we care about? wouldn't we need to do something like:

Physical.where({id : physicalID}) 

anyway?

So it would just be 

`Physical.where({id : physicalID}).comments().fetchAll()
//rather than
Photo.where({physical_id: physicalId}).fetchAll()
`

Right?

**Comment by jameslaneconkling** [comment]
Something like that, though there are a few ways to do it.

``` javascript
Physical({ id : physicalId }).comments().fetchAll().then(...)
```

would suffice (note that the .where() method is redundant, I think).  

But the main benefit would be that we could access and optionally manipulate lots of related material without making multiple API calls.  E.g. to get a Physical with all related Comments and Photos, we could make one call on the database using something like:

``` javascript
Physical({ id: physicalId }).fetch({ withRelated: ['comment', 'photo'] })
  .then(...)
```

But again, the blocker is #29 .

**Comment by jameslaneconkling** [comment]
...it also lets us run more complicated queries, like:

``` javascript
Physical().query('where', 'created_at', '>', 'some_date').fetchAll({ withRelated: ['comment', 'photo'] })

// or, if we set up Photos and Comments collections (currently, we only have Photo and Comment models)
Physical().query('where', 'created_at', '>', 'some_date').fetchAll().comments()...

// or some such
```

which otherwise would take multiple calls to the DB.  Again, I'm not 100% on this stuff, but essentially the real power of an ORM is being able to define complex joins in relatively straightforward syntax (i.e. not SQL) that hits the DB a minimal number of times, and more importantly limit the number of API calls the client needs to make.

**Comment by jameslaneconkling** [comment]
model associations are now serialized in all geojson responses.  E.g.

```
PhysicalFeature.properties.photos
// returns an array of serialized photo models

PhysicalFeature.properties.comments
// returns an array of serialized comment models
```
